"""baseline schema (tenancy, auth, jobs, lineage)

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-24 10:33:58.515607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_log_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    sa.UniqueConstraint('tenant_id', 'seq', name='uq_audit_log_tenant_seq')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_auth_sessions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions'))
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_memberships_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_membership_user_tenant')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=200), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_kind', sa.String(length=8), nullable=True),
    sa.Column('sheet_count_total', sa.Integer(), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('coverage_pct', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=4), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('arithmetic_not_evaluable', sa.Integer(), nullable=False),
    sa.Column('processing_error', sa.String(length=2000), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('ingest_notes', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_reports_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sender_identifier', sa.String(length=255), nullable=True),
    sa.Column('field_mappings', sa.JSON(), nullable=False),
    sa.Column('is_standard', sa.Boolean(), nullable=False),
    sa.Column('is_deletable', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_templates_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates'))
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_alerts_report_id_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_alerts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('exception_summaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('narrative_status', sa.String(length=32), nullable=False),
    sa.Column('aggregate', sa.JSON(), nullable=False),
    sa.Column('narrative', sa.JSON(), nullable=True),
    sa.Column('narrative_model', sa.String(length=128), nullable=True),
    sa.Column('narrative_error', sa.String(length=2000), nullable=True),
    sa.Column('narrative_warning', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_exception_summaries_report_id_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_exception_summaries_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exception_summaries'))
    )
    with op.batch_alter_table('exception_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exception_summaries_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exception_summaries_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('excluded_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_excluded_rows_report_id_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_excluded_rows_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_excluded_rows'))
    )
    with op.batch_alter_table('excluded_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_excluded_rows_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_excluded_rows_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('error_detail', sa.String(length=4000), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_jobs_report_id_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_jobs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('sheets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=False),
    sa.Column('sheet_index', sa.Integer(), nullable=False),
    sa.Column('header_row_index', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('source_column_count', sa.Integer(), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=True),
    sa.Column('samples', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('skip_reason', sa.String(length=500), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('transforms', sa.JSON(), nullable=True),
    sa.Column('trailing_blank_rows', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_sheets_report_id_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sheets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sheets'))
    )
    with op.batch_alter_table('sheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sheets_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sheets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('claim_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('sheet_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('claim_reference', sa.String(length=255), nullable=True),
    sa.Column('insured_name', sa.String(length=500), nullable=True),
    sa.Column('claim_status', sa.String(length=64), nullable=True),
    sa.Column('date_of_loss', sa.Date(), nullable=True),
    sa.Column('date_notified', sa.Date(), nullable=True),
    sa.Column('policy_reference', sa.String(length=255), nullable=True),
    sa.Column('reporting_period', sa.String(length=32), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('paid_this_month', sa.Float(), nullable=True),
    sa.Column('previously_paid', sa.Float(), nullable=True),
    sa.Column('reserve_amount', sa.Float(), nullable=True),
    sa.Column('fees_paid_this_month', sa.Float(), nullable=True),
    sa.Column('fees_previously_paid', sa.Float(), nullable=True),
    sa.Column('fees_reserve', sa.Float(), nullable=True),
    sa.Column('incurred_indemnity', sa.Float(), nullable=True),
    sa.Column('incurred_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=64), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_claim_rows_report_id_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], name=op.f('fk_claim_rows_sheet_id_sheets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_claim_rows_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_rows'))
    )
    with op.batch_alter_table('claim_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_rows_claim_reference'), ['claim_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_rows_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_rows_sheet_id'), ['sheet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_rows_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('sheet_id', sa.String(length=36), nullable=False),
    sa.Column('field_code', sa.String(length=32), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('source_column', sa.String(length=255), nullable=True),
    sa.Column('mapping_state', sa.String(length=32), nullable=False),
    sa.Column('review_state', sa.String(length=32), nullable=False),
    sa.Column('evidence', sa.String(length=1000), nullable=True),
    sa.Column('rule_version', sa.String(length=64), nullable=True),
    sa.Column('ai_model', sa.String(length=64), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_mappings_report_id_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], name=op.f('fk_mappings_sheet_id_sheets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_mappings_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mappings'))
    )
    with op.batch_alter_table('mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mappings_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mappings_sheet_id'), ['sheet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mappings_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('leakage_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('source_row_id', sa.String(length=36), nullable=False),
    sa.Column('match_row_id', sa.String(length=36), nullable=False),
    sa.Column('confidence_category', sa.String(length=16), nullable=False),
    sa.Column('amount_exposure', sa.Float(), nullable=True),
    sa.Column('matched_fields', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_row_id'], ['claim_rows.id'], name=op.f('fk_leakage_flags_match_row_id_claim_rows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_leakage_flags_report_id_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_row_id'], ['claim_rows.id'], name=op.f('fk_leakage_flags_source_row_id_claim_rows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_leakage_flags_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leakage_flags'))
    )
    with op.batch_alter_table('leakage_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leakage_flags_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leakage_flags_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('obligations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('claim_row_id', sa.String(length=36), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claim_row_id'], ['claim_rows.id'], name=op.f('fk_obligations_claim_row_id_claim_rows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_obligations_report_id_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_obligations_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_obligations'))
    )
    with op.batch_alter_table('obligations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obligations_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_obligations_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('validation_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('claim_row_id', sa.String(length=36), nullable=False),
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('rule', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['claim_row_id'], ['claim_rows.id'], name=op.f('fk_validation_results_claim_row_id_claim_rows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_validation_results_report_id_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_validation_results_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_results'))
    )
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_results_check_type'), ['check_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_results_claim_row_id'), ['claim_row_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_results_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_validation_results_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_results_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_validation_results_report_id'))
        batch_op.drop_index(batch_op.f('ix_validation_results_claim_row_id'))
        batch_op.drop_index(batch_op.f('ix_validation_results_check_type'))

    op.drop_table('validation_results')
    with op.batch_alter_table('obligations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obligations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_obligations_report_id'))

    op.drop_table('obligations')
    with op.batch_alter_table('leakage_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leakage_flags_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_leakage_flags_report_id'))

    op.drop_table('leakage_flags')
    with op.batch_alter_table('mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mappings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_mappings_sheet_id'))
        batch_op.drop_index(batch_op.f('ix_mappings_report_id'))

    op.drop_table('mappings')
    with op.batch_alter_table('claim_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_rows_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_claim_rows_sheet_id'))
        batch_op.drop_index(batch_op.f('ix_claim_rows_report_id'))
        batch_op.drop_index(batch_op.f('ix_claim_rows_claim_reference'))

    op.drop_table('claim_rows')
    with op.batch_alter_table('sheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sheets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_sheets_report_id'))

    op.drop_table('sheets')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_report_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('excluded_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_excluded_rows_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_excluded_rows_report_id'))

    op.drop_table('excluded_rows')
    with op.batch_alter_table('exception_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exception_summaries_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_exception_summaries_report_id'))

    op.drop_table('exception_summaries')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_report_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_tenant_id'))

    op.drop_table('templates')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_tenant_id'))

    op.drop_table('reports')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_tenant_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_tenant_id'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_report_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###
