"""initial schema

Revision ID: 0330b3f50409
Revises: 
Create Date: 2026-09-17 13:25:58.851423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0330b3f50409'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('sheet_count_total', sa.Integer(), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('coverage_pct', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=4), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sender_identifier', sa.String(length=255), nullable=True),
    sa.Column('field_mappings', sa.JSON(), nullable=False),
    sa.Column('is_standard', sa.Boolean(), nullable=False),
    sa.Column('is_deletable', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_report_id'), 'alerts', ['report_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_report_id'), 'audit_log', ['report_id'], unique=False)
    op.create_table('sheets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=False),
    sa.Column('sheet_index', sa.Integer(), nullable=False),
    sa.Column('header_row_index', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('skip_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sheets_report_id'), 'sheets', ['report_id'], unique=False)
    op.create_table('claim_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('sheet_id', sa.String(length=36), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('claim_reference', sa.String(length=255), nullable=True),
    sa.Column('insured_name', sa.String(length=500), nullable=True),
    sa.Column('claim_status', sa.String(length=64), nullable=True),
    sa.Column('date_of_loss', sa.Date(), nullable=True),
    sa.Column('date_notified', sa.Date(), nullable=True),
    sa.Column('policy_reference', sa.String(length=255), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('reserve_amount', sa.Float(), nullable=True),
    sa.Column('incurred_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_rows_claim_reference'), 'claim_rows', ['claim_reference'], unique=False)
    op.create_index(op.f('ix_claim_rows_report_id'), 'claim_rows', ['report_id'], unique=False)
    op.create_index(op.f('ix_claim_rows_sheet_id'), 'claim_rows', ['sheet_id'], unique=False)
    op.create_table('mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('sheet_id', sa.String(length=36), nullable=False),
    sa.Column('field_code', sa.String(length=32), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('source_column', sa.String(length=255), nullable=True),
    sa.Column('mapping_state', sa.String(length=32), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['sheets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mappings_report_id'), 'mappings', ['report_id'], unique=False)
    op.create_index(op.f('ix_mappings_sheet_id'), 'mappings', ['sheet_id'], unique=False)
    op.create_table('leakage_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('source_row_id', sa.String(length=36), nullable=False),
    sa.Column('match_row_id', sa.String(length=36), nullable=False),
    sa.Column('confidence_category', sa.String(length=16), nullable=False),
    sa.Column('amount_exposure', sa.Float(), nullable=True),
    sa.Column('matched_fields', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_row_id'], ['claim_rows.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['source_row_id'], ['claim_rows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leakage_flags_report_id'), 'leakage_flags', ['report_id'], unique=False)
    op.create_table('obligations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('claim_row_id', sa.String(length=36), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claim_row_id'], ['claim_rows.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_report_id'), 'obligations', ['report_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_row_id', sa.String(length=36), nullable=False),
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['claim_row_id'], ['claim_rows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_claim_row_id'), 'validation_results', ['claim_row_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_claim_row_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_obligations_report_id'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_index(op.f('ix_leakage_flags_report_id'), table_name='leakage_flags')
    op.drop_table('leakage_flags')
    op.drop_index(op.f('ix_mappings_sheet_id'), table_name='mappings')
    op.drop_index(op.f('ix_mappings_report_id'), table_name='mappings')
    op.drop_table('mappings')
    op.drop_index(op.f('ix_claim_rows_sheet_id'), table_name='claim_rows')
    op.drop_index(op.f('ix_claim_rows_report_id'), table_name='claim_rows')
    op.drop_index(op.f('ix_claim_rows_claim_reference'), table_name='claim_rows')
    op.drop_table('claim_rows')
    op.drop_index(op.f('ix_sheets_report_id'), table_name='sheets')
    op.drop_table('sheets')
    op.drop_index(op.f('ix_audit_log_report_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_alerts_report_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('templates')
    op.drop_table('reports')
    # ### end Alembic commands ###
