"""add arithmetic_not_evaluable to reports

Revision ID: 5896de8d5326
Revises: 0330b3f50409
Create Date: 2026-09-17 13:39:00.586743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5896de8d5326'
down_revision: Union[str, Sequence[str], None] = '0330b3f50409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('arithmetic_not_evaluable', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'arithmetic_not_evaluable')
    # ### end Alembic commands ###
