"""Object storage for uploaded source files.

Keys are generated by the server ("tenants/<uuid>/reports/<uuid>/source.<kind>")
and validated against a strict pattern -- a user-supplied filename never
becomes part of a filesystem path (forensic S1/S2). The interface is
deliberately small (put / open / delete_prefix / sha256) so an S3/Azure Blob
implementation can replace LocalObjectStore without touching callers; that
adapter is NOT implemented yet (see AI/ARCHITECTURE/TRUEBIND_TARGET_BACKEND.md).
Local writes are atomic (temp file + rename); files are created 0600."""

from __future__ import annotations

import hashlib
import os
import re
import shutil
import tempfile
from pathlib import Path

from ..config import STORAGE_DIR

_KEY_RE = re.compile(r"^tenants/[0-9a-f-]{36}/reports/[0-9a-f-]{36}/source\.(xlsx|xlsm|xls|csv)$")


def source_key(tenant_id: str, report_id: str, kind: str) -> str:
    """kind is the file-gate verdict (signature-checked), never the raw
    upload name; parsers pick their reader from this extension."""
    key = f"tenants/{tenant_id}/reports/{report_id}/source.{kind}"
    if not _KEY_RE.match(key):
        raise ValueError("invalid storage key")
    return key


class LocalObjectStore:
    def __init__(self, root: Path | None = None):
        self.root = Path(root or STORAGE_DIR).resolve()

    def _path(self, key: str) -> Path:
        if not _KEY_RE.match(key):
            raise ValueError("invalid storage key")
        p = (self.root / key).resolve()
        if self.root not in p.parents:
            raise ValueError("invalid storage key")
        return p

    def put_file(self, key: str, src: Path) -> str:
        """Moves `src` into the store; returns its SHA-256."""
        dest = self._path(key)
        dest.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
        digest = sha256_file(src)
        fd, tmp = tempfile.mkstemp(dir=dest.parent, prefix=".upload-")
        os.close(fd)
        shutil.move(str(src), tmp)
        os.chmod(tmp, 0o600)
        os.replace(tmp, dest)
        return digest

    def local_path(self, key: str) -> Path:
        p = self._path(key)
        if not p.exists():
            raise FileNotFoundError("stored source file is missing")
        return p

    def delete_report(self, tenant_id: str, report_id: str) -> None:
        d = self._path(source_key(tenant_id, report_id, "csv")).parent
        shutil.rmtree(d, ignore_errors=True)


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


store = LocalObjectStore()
