"""initial schema: reports, leakage_flags, audit_log, templates, obligations, alerts

Revision ID: 2cb3bdbe538e
Revises: 
Create Date: 2026-09-17 11:48:16.928606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb3bdbe538e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.String(length=200), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sheets_total', sa.Integer(), nullable=False),
    sa.Column('sheets_processed', sa.Integer(), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_assessed', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('score_reliable', sa.Boolean(), nullable=False),
    sa.Column('summary_json', sa.Text(), nullable=False),
    sa.Column('segregated_export_path', sa.String(length=1000), nullable=True),
    sa.Column('health_report_xlsx_path', sa.String(length=1000), nullable=True),
    sa.Column('health_report_pdf_path', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('template_type', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deletable', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=200), nullable=True),
    sa.Column('before_value', sa.Text(), nullable=True),
    sa.Column('after_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leakage_flags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('sheet_a', sa.String(length=200), nullable=False),
    sa.Column('row_a', sa.Integer(), nullable=False),
    sa.Column('claim_ref_a', sa.String(length=200), nullable=True),
    sa.Column('insured_name_a', sa.String(length=500), nullable=True),
    sa.Column('amount_a', sa.Float(), nullable=True),
    sa.Column('sheet_b', sa.String(length=200), nullable=False),
    sa.Column('row_b', sa.Integer(), nullable=False),
    sa.Column('claim_ref_b', sa.String(length=200), nullable=True),
    sa.Column('insured_name_b', sa.String(length=500), nullable=True),
    sa.Column('amount_b', sa.Float(), nullable=True),
    sa.Column('matched_fields', sa.Text(), nullable=False),
    sa.Column('amount_exposure', sa.Float(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer', sa.String(length=200), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obligations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('linked_entity_type', sa.String(length=100), nullable=True),
    sa.Column('linked_entity_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_field_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('header_text', sa.String(length=300), nullable=False),
    sa.Column('field_code', sa.String(length=20), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=200), nullable=True),
    sa.Column('obligation_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('template_field_mappings')
    op.drop_table('obligations')
    op.drop_table('leakage_flags')
    op.drop_table('audit_log')
    op.drop_table('templates')
    op.drop_table('reports')
    # ### end Alembic commands ###
